---
title: "R Notebook"
output: html_notebook
---


```{r}
library(sp)
library(dplyr)
setwd("../")
getwd()
```


```{r}
################################
#########change this############
################################
load('taxi2016_9.RData')

load('../output/nyc_nbhd.RData')
weather<-read.csv('../data/weather_small.csv',as.is=TRUE)
#taxi2016_9
```


###check
```{r}
(a_raw<-dim(taxi2016_9))
head(taxi2016_9)
```


add filter condition
```{r}
filtaxi <- taxi2016_9%>%
  mutate(fpd=fare_amount/trip_distance)%>%
  filter(trip_distance<80 & trip_distance>0)%>%
  filter(fare_amount<200 & fare_amount>0)%>%
  filter(fpd<10 & fpd>0.5)
(b_filter<-dim(filtaxi))
#filtaxi%>%select(fpd)%>%boxplot()
```


add neighborhood
It may take time.
```{r}
nbhd<-function(ll){
  colnames(ll)=c('lon','lat')
  ll_spdf<-ll
  coordinates(ll_spdf)= ~lon + lat
  proj4string(ll_spdf) <- proj4string(nyc_nbhd)
  match<-over(ll_spdf, nyc_nbhd)
  return(match[,c(1,3)])
}

punbhd<-filtaxi%>%
  select(pickup_longitude,pickup_latitude)%>%
  nbhd()
colnames(punbhd)<-c('PUnbhd','PUnbhdBorough')


donbhd<-filtaxi%>%
  select(pickup_longitude,pickup_latitude)%>%
  nbhd()
colnames(donbhd)<-c('DOnbhd','DOnbhdBorough')
```


###check
```{r}
#dim(punbhd)
#dim(donbhd)
```


combine new nbhd column
```{r}
taxitemp<-cbind(filtaxi,punbhd,donbhd)
dim(taxitemp)
```


delete NA values
```{r}
taxitemp1<- taxitemp%>%na.omit()
(c_nbhd_naomit<-dim(taxitemp1))
```

```{r}
head(taxitemp1)
```


add weather
```{r}
taxitemp2<-taxitemp1%>%mutate(pu_wl=if_else(PUnbhdBorough %in% c('Manhattan', 'Bronx', 'Unknown')
                                            , 'NY CITY CENTRAL PARK, NY US',
                             if_else(PUnbhdBorough %in% c('Brooklyn','Queens')
                                     , 'LA GUARDIA AIRPORT, NY US'
                                     ,'WOODBRIDGE TWP 1.1 ESE, NJ US')))
taxitemp3<-taxitemp2%>%mutate(do_wl=if_else(DOnbhdBorough %in% c('Manhattan', 'Bronx', 'Unknown')
                                            , 'NY CITY CENTRAL PARK, NY US',
                             if_else(DOnbhdBorough %in% c('Brooklyn','Queens')
                                     , 'LA GUARDIA AIRPORT, NY US'
                                     ,'WOODBRIDGE TWP 1.1 ESE, NJ US')))

#left join weather data
pu_weather<-taxitemp3%>%left_join(weather,by=c('pickup_date'='DATE','pu_wl'='NAME'))%>%select(BAD_WEATHER)
colnames(pu_weather)<-'pu_bad_weather'
do_weather<-taxitemp3%>%left_join(weather,by=c('dropoff_date'='DATE','do_wl'='NAME'))%>%select(BAD_WEATHER)
colnames(do_weather)<-'do_bad_weather'
taxitemp4<-cbind(taxitemp1,pu_weather,do_weather)
d_final<-dim(taxitemp4%>%na.omit())
```


######aggregate data
```{r}
PU<- taxitemp4%>%
  group_by(pickup_date, pickup_hour, PUnbhd, PUnbhdBorough, pu_bad_weather)%>%
  summarize(totaldist=sum(trip_distance),
            totalfare=sum(fare_amount),
            count=n())%>%
  select(pickup_date, pickup_hour, PUnbhd, PUnbhdBorough, pu_bad_weather, totaldist, totalfare, count)

DO<- taxitemp4%>%
  group_by(dropoff_date, dropoff_hour, DOnbhd, DOnbhdBorough, do_bad_weather)%>%
  summarize(totaldist=sum(trip_distance),
            totalfare=sum(fare_amount),
            count=n())%>%
  select(dropoff_date, dropoff_hour, DOnbhd, DOnbhdBorough, do_bad_weather, totaldist, totalfare, count)
```


check
```{r}
#xx=taxitemp1%>%group_by(PUnbhd,PUnbhdBorough)%>%tally()
#sum(table(xx$PUnbhd)>1)
#dim(PUcount)
#dim(DOcount)
#dim(PUfpd)
#dim(DOfpd)
dim(PU)
dim(DO)
head(PU)
head(DO)
dim<-rbind(a_raw,b_filter,c_nbhd_naomit,d_final)
#ex=DO%>%filter(DOnbhd=='Upper West Side')
#ex%>%mutate(fpd=totalfare/totaldist)
```



```{r}
save(PU, DO, dim, file = "update_taxi9example.RData")
```





