---
title: "R Notebook"
output: html_notebook
---

```{r}
library(sp)
library(dplyr)
setwd("../")
getwd()
```

```{r}
load('../output/nyc_nbhd.RData')
taxi1<-read.csv('../output/taxi2016_1.csv')
taxi2<-read.csv('../output/taxi2016_2.csv')
weather<-read.csv('../data/weather_small.csv',as.is=TRUE)
#nyc_neighborhoods
```

```{r}
taxiall <- rbind(taxi1,taxi2)
```

```{r}
a <- 0
for(i in unique(sort(taxiall$PU.zone))){
  if(i %in% unique(nyc_nbhd@data$neighborhood)){
    a = a+1
  }
  #print(i)
}
#unique(sort(taxiall$PU.zone))
```


```{r}
unique(nyc_nbhd@data$neighborhood)
```


```{r}
nbhd<-function(ll){
  colnames(ll)=c('lon','lat')
  ll_spdf<-ll
  coordinates(ll_spdf)= ~lon + lat
  proj4string(ll_spdf) <- proj4string(nyc_nbhd)
  match<-over(ll_spdf, nyc_nbhd)
  return(match[,c(1,3)])
}

#taxi1
pickupnbhd1<-taxi1%>%select(PU.lon,PU.lat)%>%nbhd()
colnames(pickupnbhd1)<-c('PUnbhd','PUnbhdBorough')


dropoffnbhd1<-taxi1%>%select(DO.lon,DO.lat)%>%nbhd()
colnames(dropoffnbhd1)<-c('DOnbhd','DOnbhdBorough')

#taxi2
pickupnbhd2<-taxi2%>%select(PU.lon,PU.lat)%>%nbhd()
colnames(pickupnbhd2)<-c('PUnbhd','PUnbhdBorough')


dropoffnbhd2<-taxi2%>%select(DO.lon,DO.lat)%>%nbhd()
colnames(dropoffnbhd2)<-c('DOnbhd','DOnbhdBorough')
```

```{r}
updatetaxi1<-cbind(taxi1,pickupnbhd1,dropoffnbhd1)
updatetaxi2<-cbind(taxi2,pickupnbhd2,dropoffnbhd2)
taxidata<-rbind(updatetaxi1,updatetaxi2)
```


```{r}
#A<-taxiall%>%select(PU.lon,PU.lat)%>%nbhd()
```

```{r}
#unique(taxiall$neighborhood)
```


```{r}
#add columns
taxidata<-taxidata%>%mutate(pu_date=substring(tpep_pickup_datetime,1,10),do_date=substring(tpep_dropoff_datetime,1,10))
taxidatatemp<-taxidata%>%mutate(pu_wl=if_else(PU.Borough %in% c('Manhattan', 'Bronx', 'Unknown'), 'NY CITY CENTRAL PARK, NY US',
                             if_else(PU.Borough %in% c('Brooklyn','Queens'), 'LA GUARDIA AIRPORT, NY US','WOODBRIDGE TWP 1.1 ESE, NJ US')))
taxidatatemp<-taxidatatemp%>%mutate(do_wl=if_else(DO.Borough %in% c('Manhattan', 'Bronx', 'Unknown'), 'NY CITY CENTRAL PARK, NY US',
                             if_else(DO.Borough %in% c('Brooklyn','Queens'), 'LA GUARDIA AIRPORT, NY US','WOODBRIDGE TWP 1.1 ESE, NJ US')))

#left join weather data
pu_weather<-taxidatatemp%>%left_join(weather,by=c('pu_date'='DATE','pu_wl'='NAME'))%>%select(BAD_WEATHER)
colnames(pu_weather)<-'pu_weather'
do_weather<-taxidatatemp%>%left_join(weather,by=c('do_date'='DATE','do_wl'='NAME'))%>%select(BAD_WEATHER)
colnames(do_weather)<-'do_weather'
taxi<-cbind(taxidata,pu_weather,do_weather)
```

```{r}
#clean taxi data and add FPD column
# taxi <- taxi %>% filter(trip_distance>0) %>% 
#   filter(fare_amount > 0) %>% 
#   filter(trip_distance!=3180000) %>% 
#   mutate(FPD=fare_amount/trip_distance) %>% filter(FPD <= 15)
```

```{r}
All_FPD <- na.omit(taxi %>% filter(trip_distance>0) %>% 
  filter(fare_amount > 0) %>% 
  filter(trip_distance!=3180000) %>% select(PUnbhd,PU.hour,fare_amount,trip_distance)%>%group_by(PU.hour, PUnbhd) %>%
  mutate(FPD=sum(fare_amount)/sum(trip_distance)) %>% select(PUnbhd,PU.hour,FPD))

```

```{r}
All_FPD
```


```{r}
#boxplot(taxi$FPD)
```

```{r}
All_FPD <- All_FPD %>% mutate(FPD_level = ifelse(FPD>=0 & FPD < 1, 0,
                                   ifelse(FPD>=1 & FPD < 2,1,
                                          ifelse(FPD>=2 & FPD < 3,2,
                                                 ifelse(FPD>=3 & FPD < 4,3,
                                                        ifelse(FPD>=4 & FPD < 5,4,
                                                               ifelse(FPD>=5 & FPD < 6,5,
                                                                      ifelse(FPD>=6 & FPD < 7,6,7))))))))
```

```{r}
All_FPD
```


```{r}
#taxi <- A
```

```{r}
All_Count <- taxi %>% group_by(PUnbhd,PU.hour) %>% tally()
names(All_Count) <- c("PUnbhd","PU.hour","Count")
All_Count
```


```{r}
#head(taxi)
#FPD_result <- taxi %>% group_by(FPD,FPD_level,PUnbhd) %>% tally()
WWW <- geo_join(nyc_nbhd, All_FPD, "neighborhood", "PUnbhd")
#TTT <- geo_join(nyc_nbhd, All_Count, "neighborhood", "PUnbhd")
```

```{r}
table(na.omit(WWW@data)$FPD_level)
cbind(All_Count,All_FPD,by="PUnbhd")
# hist(FPD_result$FPD)
# hist(x=FPD_result$FPD_level)
# hist(na.omit(WWW@data$FPD))
```


```{r}
#save(taxi, file = "/Users/yeyejiang/Desktop/taxidata.RData")
save(taxi, file = "../output/taxidata.RData")
```

