---
title: "R Notebook"
output: html_notebook
---

```{r}
library(sp)
library(dplyr)
# setwd("../")
# getwd()
```

```{r}
load('taxi2016_FinalClean.RData')
#load('../output/taxidata.RData')
# taxi1<-read.csv('../output/taxi2016_1.csv')
# taxi2<-read.csv('../output/taxi2016_2.csv')
# taxiall <- rbind(taxi1,taxi2)
#weather<-read.csv('../data/weather_small.csv',as.is=TRUE)
#nyc_neighborhoods
```

```{r}
All_FPD <- na.omit(AllFPD <- PU %>% group_by(pickup_hour, PUnbhd) %>% mutate(FPD=sum(totalfare)/sum(totaldist))) %>% select(pickup_hour, PUnbhd,FPD) %>% unique()
All_FPD
```

```{r}
SunnyFPD <- PU %>% filter(pu_bad_weather==0)%>%
  group_by(pickup_hour, PUnbhd) %>%
  mutate(FPD=sum(totalfare)/sum(totaldist))%>% 
  select(pickup_hour, PUnbhd,FPD) %>% unique()
```

```{r}
BadFPD <- PU %>% filter(pu_bad_weather==1)%>%
  group_by(pickup_hour, PUnbhd) %>%
  mutate(FPD=sum(totalfare)/sum(totaldist))%>% 
  select(pickup_hour, PUnbhd,FPD) %>% unique()
```


```{r}
add_level <- function(df){
  A <- df %>% mutate(FPD_level = ifelse(FPD>=0 & FPD < 1, 0,
                                   ifelse(FPD>=1 & FPD < 2,1,
                                          ifelse(FPD>=2 & FPD < 3,2,
                                                 ifelse(FPD>=3 & FPD < 4,3,
                                                        ifelse(FPD>=4 & FPD < 5,4,
                                                               ifelse(FPD>=5 & FPD < 6,5,
                                                                      ifelse(FPD>=6 & FPD < 7,6,7))))))))
  return(A)
}
AllFPD <- add_level(All_FPD)
SunnyFPD <- add_level(SunnyFPD)
BadFPD <- add_level(BadFPD)
```

```{r}
AllFPD2 <- DO %>% group_by(dropoff_hour, DOnbhd) %>%
  mutate(FPD=sum(totalfare)/sum(totaldist))%>% 
  select(dropoff_hour, DOnbhd,FPD) %>% unique()
SunnyFPD2 <- DO %>% filter(do_bad_weather==0)%>%
  group_by(dropoff_hour, DOnbhd) %>%
  mutate(FPD=sum(totalfare)/sum(totaldist))%>% 
  select(dropoff_hour, DOnbhd,FPD) %>% unique()

BadFPD2 <- DO %>% filter(do_bad_weather==1)%>%
  group_by(dropoff_hour, DOnbhd) %>%
  mutate(FPD=sum(totalfare)/sum(totaldist))%>% 
  select(dropoff_hour, DOnbhd,FPD) %>% unique()
```

```{r}
AllFPD2 <- add_level(AllFPD2)
SunnyFPD2 <- add_level(SunnyFPD2)
BadFPD2 <- add_level(BadFPD2)
```

```{r}
AllFPD2
```


```{r}
Allcount <- PU %>% group_by(PUnbhd,pickup_hour)%>%mutate(totalcount=sum(count)) %>% 
  select(PUnbhd,pickup_hour,totalcount) %>% unique()

Sunnycount <- PU %>%filter(pu_bad_weather==0) %>% 
  group_by(PUnbhd,pickup_hour)%>%mutate(totalcount=sum(count))%>% 
  select(PUnbhd,pickup_hour,totalcount) %>% unique()

Badcount <- PU %>%filter(pu_bad_weather==1) %>%
  group_by(PUnbhd,pickup_hour)%>%mutate(totalcount=sum(count))%>% 
  select(PUnbhd,pickup_hour,totalcount) %>% unique()



Allcount2 <- DO %>% group_by(DOnbhd,dropoff_hour)%>%
  mutate(totalcount=sum(count))%>% 
  select(DOnbhd,dropoff_hour,totalcount) %>% unique()

Sunnycount2 <- DO %>%filter(do_bad_weather==0) %>% 
  group_by(DOnbhd,dropoff_hour)%>%
  mutate(totalcount=sum(count))%>% 
  select(DOnbhd,dropoff_hour,totalcount) %>% unique()

Badcount2 <- DO %>%filter(do_bad_weather==1) %>%
  group_by(DOnbhd,dropoff_hour)%>%mutate(totalcount=sum(count))%>% 
  select(DOnbhd,dropoff_hour,totalcount) %>% unique()
```

```{r}

```


```{r}
save(Allcount,Sunnycount,Badcount,AllFPD,SunnyFPD,BadFPD,file = "PU_data.RData")
save(Allcount2,Sunnycount2,Badcount2,AllFPD2,SunnyFPD2,BadFPD2,file = "DO_data.RData")
```

