---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(reshape2)
library(ggmap)
library(tigris)
library(leaflet)
library(sp)
load('/Users/yeyejiang/Desktop/DO_data.RData')
load('/Users/yeyejiang/Documents/GitHub/Spring2019-Proj2-grp11/output/nyc_nbhd.RData')
#Allcount2$DOnbhd=as.character(Allcount2$DOnbhd)
dim(Allcount2)
```

create tttbbb(from 0:00-23:00)
```{r}
tttbbb=dcast(Allcount2,DOnbhd~dropoff_hour, value.var='totalcount')
tttbbb[is.na(tttbbb)] <- 0
rownames(tttbbb)=tttbbb[,1]
tttbbb=tttbbb[2:25]
# tttbbb['Central Park',]
# tttbbb[38,] 
# which.max(tttbbb[38,] )
# 16
# tttbbb
```

create drtb(from 4:00am - 3:00am)
```{r}
lllll=which(apply(tttbbb>200,1,sum)==24)
uuuuu=which(apply((tttbbb<200&tttbbb>100),1,sum)>5)
drtb=tttbbb[,c(5:24,1:4)]
```


add smooth line(from 4:00am - 3:00am)
```{r}
x=c(1:24)
pred=function(y){
  lo <- loess(y~x)
  value=predict(lo, data.frame(c(1:24)), se = TRUE)$fit
  value
}
(predtable=apply(drtb,1,'pred'))
```


temp(check concave position)
```{r}
countconvex=function(z){
  c=diff(z)%>%sign()%>%diff()
  return(c==-2)
}
convextable=apply(predtable,2,'countconvex')
#convextable[,38]
#dim(convextable)
#which(convextable[,20]=='TRUE')+1
```


return concave
```{r}
whichcountconvex=function(z){
  c=diff(z)%>%sign()%>%diff()
  return(as.integer(which(c==-2)+5))
}
peak=apply(predtable,2,'whichcountconvex')
peak[[38]]
```


define
```{r}
nbhd<-rownames(tttbbb)
xx=c(1:254)
for (i in 1:254){
  xx[i]=if_else(sum(peak[[i]] %in% c(14:16)) ==1, 'Attractions',
                if_else(length(peak[[i]])==2, 'Work Area', 
                         if_else(sum(peak[[i]] %in% c(21:23)) ==1, 'Entertainment', 'Else'
                               #  if_else((apply(predtable,2,which.max) %in% c(21:24,1))=='TRUE','Residential Area', 'Else'
                                #         )
                                 )
                         )
                )
}
tempt<-data.frame(cbind(nbhd,xx))
tempt$xx<-as.character(tempt$xx)

if_res<-apply(predtable,2,which.max) %in% c(21:24,1)
if_els<-tempt$xx=='Else'



tempt[if_res+if_els==2,]$xx='Residential Area'
table(tempt[,'xx'])
tempt<-tempt%>%mutate('index'= if_else(xx=='Attractions',5,
                              if_else(xx=='Entertainment',2,
                                      if_else(xx=='Residential Area',3,
                                              if_else(xx=='Work Area', 4,1)
                                      ))))
```

```{r}
save(tempt,file ='/Users/yeyejiang/Desktop/cluster.RData')
```



```{r}



# #color = list(color1 = c('#F2D7D5','#D98880', '#CD6155', '#C0392B', '#922B21','#641E16'),
# #            color2 = c('#e6f5ff','#abdcff', '#70c4ff', '#0087e6', '#005998','#00365d','#1B4F72'))
# #pal2 <- colorBin(color[[1]], bins=c(1:5))
# pal<- colorBin(c('red','blue','green','purple', 'grey'), bins=c(1:5))
# pal1 <- colorBin(color[[2]], bins=c(1:5))
# pal2 = colorBin(c("#882E72", "#B178A6", "#D6C1DE", "#1965B0", "#5289C7", "#7BAFDE", "#4EB265", "#90C987", "#CAE0AB", "#F7EE55", "#F6C141", "#F1932D", "#E8601C", "#DC050C"), 1:10)
# color = list(color1 = c('#F2D7D5','#D98880', '#CD6155', '#C0392B', '#922B21','#641E16'),
#              color2 = c('#e6f5ff','#abdcff', '#70c4ff', '#0087e6', '#005998','#00365d','#1B4F72'),
#              color3 = c("#F7FCF5","#74C476", "#005A32"))
# label = list(label1 = c("<100","100-1000","1000~10,000","10,000~100,000","100,000~1,000,000","1,000,000~10,000,000"),
#              label2 = c("0-1","2-3","3-4","4-5","5-6","6","7+"),
#              label3 = c("<0.4","0.4~0.6",">0.6"))
map_data <- geo_join(nyc_nbhd, tempt, "neighborhood", "nbhd")

leaflet(map_data) %>%
  addTiles() %>% 
  addPolygons(fillColor = ~pal2(index), popup = ~neighborhood, color = 'grey', weight = 1) %>% 
  addProviderTiles("CartoDB.Positron") %>%
  setView(-73.98, 40.75, zoom = 13)
```




```{r}
par(mfrow=c(5,6))
for (i in 1:30){
  a=lllll[i]
  plot(c(0,0,0,predtable[,a]),ylab=paste(colnames(predtable)[a]))
}

par(mfrow=c(5,6))
for (i in 1:30){
  a=uuuuu[i]
  plot(c(0,0,0,predtable[,a]),ylab=paste(colnames(predtable)[a]))
}



tb[lllll[28],]

```










```{r}
#lllll=which(apply(tttbbb>200,1,sum)==24)
#dim(lllll)
```



















